apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: ingress 
spec:
  ingressClassName: nginx-ingress
  rules:
  - https: 
      paths: 
      - path: /
        backend:
          serviceName: nginx-service
          servicePort: 443
