apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-deployment
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #   - vannaboth.info
  #   secretName: certificate-secret
  rules:
  - host: "vannaboth.info"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:  
            name: wordpress-service
            port:
              number: 8080
