apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: ingress
  annotations:
    #Allow TLS passthrough with an Ingress annotation
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    #Allow HTTP request to redirect HTTPs
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx-ingress
  tls: 
  - hosts:
    - starkdomain.me 
    secretName: certificate-secret
  rules:
  - host: starkdomain.me 
    http: 
      paths: 
      - pathType: Prefix 
        path: /
        backend:
          service:
            name: wordpress-service
          port:
            number: 8080
