apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: ingress-nginx
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template: 
    metadata:
      labels:
        app: mariadb 
    spec: 
      containers:
      - name: mariadb
        image: mariadb:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "1"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 3306 
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-root-password
              optional: false
        - name: MARIADB_DATABASE
          value: wordpress
        - name: MARIADB_USER
          value: root
        volumeMounts:
        - name: mariadb-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-pv
        persistentVolumeClaim:
          claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-internal-service
  namespace: ingress-nginx
spec:
  selector:
    app: mariadb
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30004
