services:
  jenkins-blueocean:
    image: jenkins
    container_name: jenkins-blueocean 
    environment:
      - DOCKER_TLS_VERIFY=1
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_CERT_PATH=/certs/client
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    expose:
      - 8080
      - 50000
    ports:
      - '8080:8080'    
    networks:
      - jenkins
    dns:
      - 8.8.8.8       
    restart: on-failure
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    expose:
      - 9090
    ports:
      - '9090:9090'
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - jenkins
    restart: on-failure
  grafana:
    image: grafana/grafana
    container_name: grafana
    expose:
      - 3000
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana 
    networks:
      - jenkins
    restart: on-failure

volumes:
  jenkins-data:
  jenkins-docker-certs:
  prometheus-data:
  grafana-storage:

networks:
  jenkins:
    driver: bridge
