services:
  jenkins-blueocean:
    image: jenkins
    container_name: jenkins-blueocean 
    environment:
      - DOCKER_TLS_VERIFY=1
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_CERT_PATH=/certs/client
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    expose:
      - 8080
      - 50000
    ports:
      - '8080:8080'    
    networks:
      - jenkins
    dns:
      - 8.8.8.8       
    restart: on-failure
volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins:
    driver: bridge
