- name: Remove nginx service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    namespace: ingress-nginx
    name: "{{ nginx_svc }}"
  tags: nginx-svc

- name: Remove mariadb service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    namespace: ingress-nginx
    name: "{{ mariadb_svc }}"
  tags: mariadb-svc

- name: Remove wordpress service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    namespace: ingress-nginx
    name: "{{ wordpress_svc }}"
  tags: wordpress-svc

- name: Remove ingress controller svc 
  kubernetes.core.k8s:
    state: absent
    api_version: v1 
    kind: Service 
    namespace: ingress-nginx
    name: "{{ controller }}"
  tags: controller-svc

- name: Remove ingress controller-admission
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    namespace: ingress-nginx
    name: "{{ controller_admission }}"
  tags: controller-admission