# - name: Delete nginx_configmap from namespace
#   kubernetes.core.k8s:
#     api_version: v1
#     namespace: ingress-nginx
#     kind: ConfigMap
#     name: "{{ nginx_configmap }}"
#     state: absent
#   tags: delete_nginx_configmap

# - name: Delete wordpress_configmap from namespace
#   kubernetes.core.k8s:
#     api_version: v1
#     namespace: ingress-nginx
#     kind: ConfigMap
#     state: absent
#   loop:
#     - "{{ apache_configmap }}"
#     - "{{ port_configmap }}"
#   tags: delete_wordpress_configmap

- name: Delete mariadb_configmap from namespace
  kubernetes.core.k8s:
    api_version: v1
    namespace: ingress-nginx
    kind: ConfigMap
    name: "{{ mariadb_configmap }}"
    state: absent
  tags: delete_mariadb_configmap

- name: Delete mariadb_volume from namespace
  kubernetes.core.k8s:
    api_version: v1
    namespace: ingress-nginx
    kind: PersistentVolume
    name: "{{ mariadb_volume }}"
    state: absent
  tags: delete_mariadb_volume

- name: Delete mariadb_secret from namespace
  kubernetes.core.k8s:
    api_version: v1
    namespace: ingress-nginx
    kind: Secret
    name: "{{ mariadb_secret }}"
    state: absent
  tags: delete_mariadb_secret

- name: Delete certificate_secret from namespace 
  kubernetes.core.k8s:
    api_version: v1
    namespace: ingress-nginx
    kind: Secret 
    name: "{{ certificate_secret }}"
    state: absent
  tags: delete_certificate_secret
