- name: Delete nginx Deployment from namespace
  kubernetes.core.k8s:
    api_version: apps/v1
    namespace: default
    kind: Deployment
    name: "{{ nginx }}"
    state: absent
  tags: delete_nginx

- name: Delete mariadb Deployment from namespace
  kubernetes.core.k8s:
    api_version: apps/v1
    namespace: default
    kind: Deployment
    name: "{{ mariadb }}"
    state: absent
  tags: delete_mariadb

- name: Delete wordpress Deployment from namespace
  kubernetes.core.k8s:
    api_version: apps/v1
    namespace: default
    kind: Deployment
    name: "{{ wordpress }}"
    state: absent
  tags: delete_wordpress

- name: Delete ingress Deployment from namespace
  kubernetes.core.k8s:
    api_version: apps/v1
    namespace: ingress-nginx
    kind: Deployment
    name: "{{ ingress }}"
    state: absent
  tags: delete_ingress

# - name: Delete all Deployment from namespace
#   kubernetes.core.k8s:
#     api_version: apps/v1
#     namespace: default
#     kind: Deployment
#     delete_all: true
#   tags: delete_all