# - name: Delete nginx_configmap from namespace
#   kubernetes.core.k8s:
#     api_version: v1
#     namespace: ingress-nginx
#     kind: ConfigMap
#     name: "{{ nginx_configmap }}"
#     state: absent
#   tags: delete_nginx_configmap

- name: Delete apache_configmap from namespace
  kubernetes.core.k8s:
    api_version: v1
    namespace: ingress-nginx
    kind: ConfigMap
    state: absent
    name: apache-template 
  tags: delete_wordpress_configmap

- name: Delete port_configmap from namespace
  kubernetes.core.k8s:
    api_version: v1
    namespace: ingress-nginx
    kind: ConfigMap
    state: absent
    name: port-template 
  tags: delete_wordpress_configmap

- name: Delete mariadb_configmap from namespace
  kubernetes.core.k8s:
    api_version: v1
    namespace: ingress-nginx
    kind: ConfigMap
    name: mariadb-configmap
    state: absent
  tags: delete_mariadb_configmap

- name: Delete mariadb_volume from namespace
  kubernetes.core.k8s:
    api_version: v1
    namespace: ingress-nginx
    kind: PersistentVolumeClaim
    name: mariadb-pvc 
    state: absent
  tags: delete_mariadb_volume

- name: Delete mariadb_secret from namespace
  kubernetes.core.k8s:
    api_version: v1
    namespace: ingress-nginx
    kind: Secret
    name: mariadb-secret 
    state: absent
  tags: delete_mariadb_secret

- name: Delete certificate_secret from namespace 
  kubernetes.core.k8s:
    api_version: v1
    namespace: ingress-nginx
    kind: Secret 
    name: certificate-secret
    state: absent
  tags: delete_certificate_secret
