- name: Deploy mariadb volume 
  kubernetes.core.k8s: 
    state: present 
    src: "{{ mariadb_volume }}"
    namespace: ingress-nginx
  tags: mariadb-volume

- name: Deploy mariadb configmap 
  kubernetes.core.k8s:
    state: present
    src: "{{ mariadb_configmap }}"
    namespace: ingress-nginx
  tags: mariadb-configmap

- name: Deploy mariadb secret 
  kubernetes.core.k8s:
    state: present 
    src: "{{ mariadb_secret }}"
    namespace: ingress-nginx
  tags: mariadb-secret

# - name: Deploy nginx configmap 
#   kubernetes.core.k8s:
#     state: present 
#     src: "{{ nginx_configmap }}"
#     namespace: ingress-nginx
#   tags: nginx-configmap 

- name: Deploy wordpress configmap 
  kubernetes.core.k8s:
    state: present 
    src: "{{ wordpress_configmap }}"
    namespace: ingress-nginx
  tags: wordpress-configmap

- name: Deploy certificate-secret
  kubernetes.core.k8s:
    state: present 
    src: "{{ certificate_secret }}"
    namespace: ingress-nginx
  tags: certificate-secret