# - name: Deploy mariadb volume 
#   kubernetes.core.k8s: 
#     state: present 
#     src: "{{ mariadb_volume }}"
#   tags: mariadb-volume

- name: Deploy mariadb configmap 
  kubernetes.core.k8s:
    state: present
    src: "{{ mariadb_configmap }}"
  tags: mariadb-configmap

- name: Deploy mariadb secret 
  kubernetes.core.k8s:
    state: present 
    src: "{{ mariadb_secret }}"
  tags: mariadb-secret

- name: Deploy nginx configmap 
  kubernetes.core.k8s:
    state: present 
    src: "{{ nginx_configmap }}"
  tags: nginx-configmap 

- name: Deploy wordpress configmap 
  kubernetes.core.k8s:
    state: present 
    src: "{{ wordpress_configmap }}"
  tags: wordpress-configmap