- name: Deploy ingress
  kubernetes.core.k8s:
    state: present 
    src: "{{ deploy_ingress }}"
    namespace: ingress-nginx
  tags: deploy-ingress

- name: Deploy nginx to cluster
  kubernetes.core.k8s:
    state: present
    src: "{{ deploy_nginx }}"
    namespace: ingress-nginx
  tags: deploy-nginx

- name: Deploy wordpress to cluster
  kubernetes.core.k8s:
    state: present 
    src: "{{ deploy_wordpress }}"
    namespace: ingress-nginx
  tags: deploy-wordpress

- name: Deploy mariadb to cluster
  kubernetes.core.k8s:
    state: present 
    src: "{{ deploy_mariadb }}"
    namespace: ingress-nginx
  tags: deploy-mariadb
