- name: Deploy controller source
  kubernetes.core.k8s:
    state: present 
    src: "{{ controller-source }}"
    namespace: ingress-nginx
  tags: deploy-ingress

- name: wait until the controller source is running 
  pause:
    second: 25
  tags: deploy-ingress

- name: Deploy ingress controller
  kubernetes.core.k8s:
    state: present 
    src: "{{ deploy_ingress }}"
    namespace: ingress-nginx
  tags: deploy-ingress

# - name: Deploy nginx to cluster
#   kubernetes.core.k8s:
#     state: present
#     src: "{{ deploy_nginx }}"
#     namespace: ingress-nginx
#   tags: deploy-nginx

- name: Deploy wordpress to cluster
  kubernetes.core.k8s:
    state: present 
    src: "{{ deploy_wordpress }}"
    namespace: ingress-nginx
  tags: deploy-wordpress

- name: Deploy mariadb to cluster
  kubernetes.core.k8s:
    state: present 
    src: "{{ deploy_mariadb }}"
    namespace: ingress-nginx
  tags: deploy-mariadb

- name: Deploy ingress config 
  kubernetes.core.k8s:
    state: present 
    src: "{{ ingress_config }}"
    namespace: ingress-nginx
  tags: deploy-ingress-config