- name: Add prometheus stack helm repo 
  kubernetes.core.helm_repository:
    name: prometheus-community
    release_namespace: ingress-nginx
    repo_url: https://prometheus-community.github.io/helm-charts
  tags: deploy_helm

- name: Deploy prometheus stack with custom value file
  kubernetes.core.helm:
    name: prometheus_stack 
    release_namespace: ingress-nginx
    chart_ref: prometheus-community/kube-prometheus-stack
    values_file:
      - "{{ custom_value }}"
    tags: deploy_helm

- name: Gather information about prometheus 
  kubernetes.core.helm_info:
    name: prometheus_stack
    release_namespace: ingress-nginx