- name: Create namespace 
  ansible.builtin.import_tasks: create-ns.yml

- name: Deploy Volumes
  ansible.builtin.import_tasks: deploy-volume.yml

- name: Deploy to kubernetes cluster
  ansible.builtin.import_tasks: deployment.yml

- name: Deploy prometheus helm 
  ansible.builtin.import_tasks: deploy-prometheus_helm.yml 