nginx: nginx-deployment
wordpress: wordpress-deployment
mariadb: mariadb-deployment
ingress: ingress-nginx-controller

nginx_svc: nginx-service
wordpress_svc: wordpress-service
mariadb_svc: mariadb-internal-service

mariadb_volume: /home/jenkins/workspace/Deployment/kubernetes/volume/mariadb-volume.yml
mariadb_configmap: /home/jenkins/workspace/Deployment/kubernetes/volume/mariadb-configmap.yml
mariadb_secret: /home/jenkins/workspace/Deployment/kubernetes/volume/mariadb-secret.yml
nginx_configmap: /home/jenkins/workspace/Deployment/kubernetes/volume/nginx-configmap.yml
wordpress_configmap: /home/jenkins/workspace/Deployment/volume/wordpress-configmap.yml
certificate_secret: /home/jenkins/workspace/Deployment/kubernetes/volume/certificate-secret.yml

