alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: telegram-receiver
      #wait after the first alert is received before sending notifications to the group.
      group_wait: 5s
      #defines the interval between subsequent notifications for the same group of alerts. 
      group_interval: 10s
      #send alert every 2 mins.
      repeat_interval: 2m
    receivers:
      - name: "telegram-receiver"
        telegram_configs:
          - send_resolved: true
            bot_token: 7753059002:AAEbeo7Tj8TPtf_cNj9nwx6rhtpDddis8GI          
            chat_id: '910787933'             
      - name: "null"
