apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  namespace: ingress-nginx
  labels:
    app: wordpress-templates
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: ingress-nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi