deploy_nginx: kubernetes/deployment/nginx-deployment.yml
deploy_wordpress: kubernetes/deployment/wordpress-deployment.yml
deploy_mariadb: kubernetes/deployment/mariadb-deployment.yml

nginx_svc: nginx-service
wordpress_svc: wordpress-service
mariadb_svc: mariadb-internal-service

mariadb_volume: /home/jenkins/workspace/Deployment/kubernetes/deployment/mariadb-volume.yml
mariadb_configmap: /home/jenkins/workspace/Deployment/kubernetes/deployment/mariadb-configmap.yml
mariadb_secret: /home/jenkins/workspace/Deployment/kubernetes/deployment/mariadb-secret.yml
nginx_configmap: /home/jenkins/workspace/Deployment/kubernetes/deployment/nginx-configmap.yml
wordpress_configmap: /home/jenkins/workspace/Deployment/deployment/wordpress-configmap.yml